/*
 * FINBOURNE Access Management API
 *
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.access.model;

import java.util.Objects;
import com.finbourne.access.model.PolicyCollectionId;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.finbourne.access.JSON;

/**
 * Request body used to add Policy Collections to a Role
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class AddPolicyCollectionToRoleRequest {
  public static final String SERIALIZED_NAME_POLICY_COLLECTIONS = "policyCollections";
  @SerializedName(SERIALIZED_NAME_POLICY_COLLECTIONS)
  private List<PolicyCollectionId> policyCollections = new ArrayList<>();

  public AddPolicyCollectionToRoleRequest() {
  }

  public AddPolicyCollectionToRoleRequest policyCollections(List<PolicyCollectionId> policyCollections) {
    
    this.policyCollections = policyCollections;
    return this;
  }

  public AddPolicyCollectionToRoleRequest addPolicyCollectionsItem(PolicyCollectionId policyCollectionsItem) {
    if (this.policyCollections == null) {
      this.policyCollections = new ArrayList<>();
    }
    this.policyCollections.add(policyCollectionsItem);
    return this;
  }

   /**
   * Identifiers of policy collections to add to a role
   * @return policyCollections
  **/
  @jakarta.annotation.Nonnull
  public List<PolicyCollectionId> getPolicyCollections() {
    return policyCollections;
  }


  public void setPolicyCollections(List<PolicyCollectionId> policyCollections) {
    this.policyCollections = policyCollections;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddPolicyCollectionToRoleRequest addPolicyCollectionToRoleRequest = (AddPolicyCollectionToRoleRequest) o;
    return Objects.equals(this.policyCollections, addPolicyCollectionToRoleRequest.policyCollections);
  }

  @Override
  public int hashCode() {
    return Objects.hash(policyCollections);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddPolicyCollectionToRoleRequest {\n");
    sb.append("    policyCollections: ").append(toIndentedString(policyCollections)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("policyCollections");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("policyCollections");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to AddPolicyCollectionToRoleRequest
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AddPolicyCollectionToRoleRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in AddPolicyCollectionToRoleRequest is not found in the empty JSON string", AddPolicyCollectionToRoleRequest.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : AddPolicyCollectionToRoleRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the json data is an array
      if (!jsonObj.get("policyCollections").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `policyCollections` to be an array in the JSON string but got `%s`", jsonObj.get("policyCollections").toString()));
      }

      JsonArray jsonArraypolicyCollections = jsonObj.getAsJsonArray("policyCollections");
      // validate the required field `policyCollections` (array)
      for (int i = 0; i < jsonArraypolicyCollections.size(); i++) {
        PolicyCollectionId.validateJsonElement(jsonArraypolicyCollections.get(i));
      };
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AddPolicyCollectionToRoleRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AddPolicyCollectionToRoleRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AddPolicyCollectionToRoleRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AddPolicyCollectionToRoleRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<AddPolicyCollectionToRoleRequest>() {
           @Override
           public void write(JsonWriter out, AddPolicyCollectionToRoleRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AddPolicyCollectionToRoleRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of AddPolicyCollectionToRoleRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of AddPolicyCollectionToRoleRequest
  * @throws IOException if the JSON string is invalid with respect to AddPolicyCollectionToRoleRequest
  */
  public static AddPolicyCollectionToRoleRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AddPolicyCollectionToRoleRequest.class);
  }

 /**
  * Convert an instance of AddPolicyCollectionToRoleRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
