/*
 * FINBOURNE Access Management API
 *
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.access.model;

import java.util.Objects;
import com.finbourne.access.model.PolicyCollectionId;
import com.finbourne.access.model.PolicyId;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.finbourne.access.JSON;

/**
 * Base properties to create or update a policy collection
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class AddToPolicyCollectionRequest {
  public static final String SERIALIZED_NAME_POLICIES = "policies";
  @SerializedName(SERIALIZED_NAME_POLICIES)
  private List<PolicyId> policies;

  public static final String SERIALIZED_NAME_POLICY_COLLECTIONS = "policyCollections";
  @SerializedName(SERIALIZED_NAME_POLICY_COLLECTIONS)
  private List<PolicyCollectionId> policyCollections;

  public AddToPolicyCollectionRequest() {
  }

  public AddToPolicyCollectionRequest policies(List<PolicyId> policies) {
    
    this.policies = policies;
    return this;
  }

  public AddToPolicyCollectionRequest addPoliciesItem(PolicyId policiesItem) {
    if (this.policies == null) {
      this.policies = new ArrayList<>();
    }
    this.policies.add(policiesItem);
    return this;
  }

   /**
   * The identifiers of the Policies to be added to the collection.
   * @return policies
  **/
  @jakarta.annotation.Nullable
  public List<PolicyId> getPolicies() {
    return policies;
  }


  public void setPolicies(List<PolicyId> policies) {
    this.policies = policies;
  }


  public AddToPolicyCollectionRequest policyCollections(List<PolicyCollectionId> policyCollections) {
    
    this.policyCollections = policyCollections;
    return this;
  }

  public AddToPolicyCollectionRequest addPolicyCollectionsItem(PolicyCollectionId policyCollectionsItem) {
    if (this.policyCollections == null) {
      this.policyCollections = new ArrayList<>();
    }
    this.policyCollections.add(policyCollectionsItem);
    return this;
  }

   /**
   * The identifiers of the PolicyCollections to be added to the collection.
   * @return policyCollections
  **/
  @jakarta.annotation.Nullable
  public List<PolicyCollectionId> getPolicyCollections() {
    return policyCollections;
  }


  public void setPolicyCollections(List<PolicyCollectionId> policyCollections) {
    this.policyCollections = policyCollections;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddToPolicyCollectionRequest addToPolicyCollectionRequest = (AddToPolicyCollectionRequest) o;
    return Objects.equals(this.policies, addToPolicyCollectionRequest.policies) &&
        Objects.equals(this.policyCollections, addToPolicyCollectionRequest.policyCollections);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(policies, policyCollections);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddToPolicyCollectionRequest {\n");
    sb.append("    policies: ").append(toIndentedString(policies)).append("\n");
    sb.append("    policyCollections: ").append(toIndentedString(policyCollections)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("policies");
    openapiFields.add("policyCollections");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to AddToPolicyCollectionRequest
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AddToPolicyCollectionRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in AddToPolicyCollectionRequest is not found in the empty JSON string", AddToPolicyCollectionRequest.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("policies") != null && !jsonObj.get("policies").isJsonNull()) {
        JsonArray jsonArraypolicies = jsonObj.getAsJsonArray("policies");
        if (jsonArraypolicies != null) {
          // ensure the json data is an array
          if (!jsonObj.get("policies").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `policies` to be an array in the JSON string but got `%s`", jsonObj.get("policies").toString()));
          }

          // validate the optional field `policies` (array)
          for (int i = 0; i < jsonArraypolicies.size(); i++) {
            PolicyId.validateJsonElement(jsonArraypolicies.get(i));
          };
        }
      }
      if (jsonObj.get("policyCollections") != null && !jsonObj.get("policyCollections").isJsonNull()) {
        JsonArray jsonArraypolicyCollections = jsonObj.getAsJsonArray("policyCollections");
        if (jsonArraypolicyCollections != null) {
          // ensure the json data is an array
          if (!jsonObj.get("policyCollections").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `policyCollections` to be an array in the JSON string but got `%s`", jsonObj.get("policyCollections").toString()));
          }

          // validate the optional field `policyCollections` (array)
          for (int i = 0; i < jsonArraypolicyCollections.size(); i++) {
            PolicyCollectionId.validateJsonElement(jsonArraypolicyCollections.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AddToPolicyCollectionRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AddToPolicyCollectionRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AddToPolicyCollectionRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AddToPolicyCollectionRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<AddToPolicyCollectionRequest>() {
           @Override
           public void write(JsonWriter out, AddToPolicyCollectionRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AddToPolicyCollectionRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of AddToPolicyCollectionRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of AddToPolicyCollectionRequest
  * @throws IOException if the JSON string is invalid with respect to AddToPolicyCollectionRequest
  */
  public static AddToPolicyCollectionRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AddToPolicyCollectionRequest.class);
  }

 /**
  * Convert an instance of AddToPolicyCollectionRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
