/*
 * FINBOURNE Access Management API
 *
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.access.model;

import java.util.Objects;
import com.finbourne.access.model.DateUnit;
import com.finbourne.access.model.PointInTimeSpecification;
import com.finbourne.access.model.RelativeToDateTime;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.finbourne.access.JSON;

/**
 * EffectiveDateRelative
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class EffectiveDateRelative {
  public static final String SERIALIZED_NAME_DATE = "date";
  @SerializedName(SERIALIZED_NAME_DATE)
  private PointInTimeSpecification date;

  public static final String SERIALIZED_NAME_ADJUSTMENT = "adjustment";
  @SerializedName(SERIALIZED_NAME_ADJUSTMENT)
  private Integer adjustment;

  public static final String SERIALIZED_NAME_UNIT = "unit";
  @SerializedName(SERIALIZED_NAME_UNIT)
  private DateUnit unit;

  public static final String SERIALIZED_NAME_RELATIVE_TO_DATE_TIME = "relativeToDateTime";
  @SerializedName(SERIALIZED_NAME_RELATIVE_TO_DATE_TIME)
  private RelativeToDateTime relativeToDateTime;

  public EffectiveDateRelative() {
  }

  public EffectiveDateRelative date(PointInTimeSpecification date) {
    
    this.date = date;
    return this;
  }

   /**
   * Get date
   * @return date
  **/
  @jakarta.annotation.Nullable
  public PointInTimeSpecification getDate() {
    return date;
  }


  public void setDate(PointInTimeSpecification date) {
    this.date = date;
  }


  public EffectiveDateRelative adjustment(Integer adjustment) {
    
    this.adjustment = adjustment;
    return this;
  }

   /**
   * Get adjustment
   * @return adjustment
  **/
  @jakarta.annotation.Nullable
  public Integer getAdjustment() {
    return adjustment;
  }


  public void setAdjustment(Integer adjustment) {
    this.adjustment = adjustment;
  }


  public EffectiveDateRelative unit(DateUnit unit) {
    
    this.unit = unit;
    return this;
  }

   /**
   * Get unit
   * @return unit
  **/
  @jakarta.annotation.Nullable
  public DateUnit getUnit() {
    return unit;
  }


  public void setUnit(DateUnit unit) {
    this.unit = unit;
  }


  public EffectiveDateRelative relativeToDateTime(RelativeToDateTime relativeToDateTime) {
    
    this.relativeToDateTime = relativeToDateTime;
    return this;
  }

   /**
   * Get relativeToDateTime
   * @return relativeToDateTime
  **/
  @jakarta.annotation.Nullable
  public RelativeToDateTime getRelativeToDateTime() {
    return relativeToDateTime;
  }


  public void setRelativeToDateTime(RelativeToDateTime relativeToDateTime) {
    this.relativeToDateTime = relativeToDateTime;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EffectiveDateRelative effectiveDateRelative = (EffectiveDateRelative) o;
    return Objects.equals(this.date, effectiveDateRelative.date) &&
        Objects.equals(this.adjustment, effectiveDateRelative.adjustment) &&
        Objects.equals(this.unit, effectiveDateRelative.unit) &&
        Objects.equals(this.relativeToDateTime, effectiveDateRelative.relativeToDateTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(date, adjustment, unit, relativeToDateTime);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EffectiveDateRelative {\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    adjustment: ").append(toIndentedString(adjustment)).append("\n");
    sb.append("    unit: ").append(toIndentedString(unit)).append("\n");
    sb.append("    relativeToDateTime: ").append(toIndentedString(relativeToDateTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("date");
    openapiFields.add("adjustment");
    openapiFields.add("unit");
    openapiFields.add("relativeToDateTime");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to EffectiveDateRelative
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!EffectiveDateRelative.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in EffectiveDateRelative is not found in the empty JSON string", EffectiveDateRelative.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!EffectiveDateRelative.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'EffectiveDateRelative' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<EffectiveDateRelative> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(EffectiveDateRelative.class));

       return (TypeAdapter<T>) new TypeAdapter<EffectiveDateRelative>() {
           @Override
           public void write(JsonWriter out, EffectiveDateRelative value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public EffectiveDateRelative read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of EffectiveDateRelative given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of EffectiveDateRelative
  * @throws IOException if the JSON string is invalid with respect to EffectiveDateRelative
  */
  public static EffectiveDateRelative fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, EffectiveDateRelative.class);
  }

 /**
  * Convert an instance of EffectiveDateRelative to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
