/*
 * FINBOURNE Access Management API
 *
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.access.model;

import java.util.Objects;
import com.finbourne.access.model.TextOperator;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.finbourne.access.JSON;

/**
 * IfIdentityClaimExpression
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class IfIdentityClaimExpression {
  public static final String SERIALIZED_NAME_CLAIM_TYPE = "claimType";
  @SerializedName(SERIALIZED_NAME_CLAIM_TYPE)
  private String claimType;

  public static final String SERIALIZED_NAME_CLAIM_VALUE_TYPE = "claimValueType";
  @SerializedName(SERIALIZED_NAME_CLAIM_VALUE_TYPE)
  private String claimValueType;

  public static final String SERIALIZED_NAME_CLAIM_ISSUER = "claimIssuer";
  @SerializedName(SERIALIZED_NAME_CLAIM_ISSUER)
  private String claimIssuer;

  public static final String SERIALIZED_NAME_CLAIM_ORIGINAL_ISSUER = "claimOriginalIssuer";
  @SerializedName(SERIALIZED_NAME_CLAIM_ORIGINAL_ISSUER)
  private String claimOriginalIssuer;

  public static final String SERIALIZED_NAME_OPERATOR = "operator";
  @SerializedName(SERIALIZED_NAME_OPERATOR)
  private TextOperator operator;

  public static final String SERIALIZED_NAME_VALUE = "value";
  @SerializedName(SERIALIZED_NAME_VALUE)
  private String value;

  public IfIdentityClaimExpression() {
  }

  public IfIdentityClaimExpression claimType(String claimType) {
    
    this.claimType = claimType;
    return this;
  }

   /**
   * Get claimType
   * @return claimType
  **/
  @jakarta.annotation.Nonnull
  public String getClaimType() {
    return claimType;
  }


  public void setClaimType(String claimType) {
    this.claimType = claimType;
  }


  public IfIdentityClaimExpression claimValueType(String claimValueType) {
    
    this.claimValueType = claimValueType;
    return this;
  }

   /**
   * Get claimValueType
   * @return claimValueType
  **/
  @jakarta.annotation.Nonnull
  public String getClaimValueType() {
    return claimValueType;
  }


  public void setClaimValueType(String claimValueType) {
    this.claimValueType = claimValueType;
  }


  public IfIdentityClaimExpression claimIssuer(String claimIssuer) {
    
    this.claimIssuer = claimIssuer;
    return this;
  }

   /**
   * Get claimIssuer
   * @return claimIssuer
  **/
  @jakarta.annotation.Nullable
  public String getClaimIssuer() {
    return claimIssuer;
  }


  public void setClaimIssuer(String claimIssuer) {
    this.claimIssuer = claimIssuer;
  }


  public IfIdentityClaimExpression claimOriginalIssuer(String claimOriginalIssuer) {
    
    this.claimOriginalIssuer = claimOriginalIssuer;
    return this;
  }

   /**
   * Get claimOriginalIssuer
   * @return claimOriginalIssuer
  **/
  @jakarta.annotation.Nullable
  public String getClaimOriginalIssuer() {
    return claimOriginalIssuer;
  }


  public void setClaimOriginalIssuer(String claimOriginalIssuer) {
    this.claimOriginalIssuer = claimOriginalIssuer;
  }


  public IfIdentityClaimExpression operator(TextOperator operator) {
    
    this.operator = operator;
    return this;
  }

   /**
   * Get operator
   * @return operator
  **/
  @jakarta.annotation.Nonnull
  public TextOperator getOperator() {
    return operator;
  }


  public void setOperator(TextOperator operator) {
    this.operator = operator;
  }


  public IfIdentityClaimExpression value(String value) {
    
    this.value = value;
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  @jakarta.annotation.Nullable
  public String getValue() {
    return value;
  }


  public void setValue(String value) {
    this.value = value;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IfIdentityClaimExpression ifIdentityClaimExpression = (IfIdentityClaimExpression) o;
    return Objects.equals(this.claimType, ifIdentityClaimExpression.claimType) &&
        Objects.equals(this.claimValueType, ifIdentityClaimExpression.claimValueType) &&
        Objects.equals(this.claimIssuer, ifIdentityClaimExpression.claimIssuer) &&
        Objects.equals(this.claimOriginalIssuer, ifIdentityClaimExpression.claimOriginalIssuer) &&
        Objects.equals(this.operator, ifIdentityClaimExpression.operator) &&
        Objects.equals(this.value, ifIdentityClaimExpression.value);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(claimType, claimValueType, claimIssuer, claimOriginalIssuer, operator, value);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IfIdentityClaimExpression {\n");
    sb.append("    claimType: ").append(toIndentedString(claimType)).append("\n");
    sb.append("    claimValueType: ").append(toIndentedString(claimValueType)).append("\n");
    sb.append("    claimIssuer: ").append(toIndentedString(claimIssuer)).append("\n");
    sb.append("    claimOriginalIssuer: ").append(toIndentedString(claimOriginalIssuer)).append("\n");
    sb.append("    operator: ").append(toIndentedString(operator)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("claimType");
    openapiFields.add("claimValueType");
    openapiFields.add("claimIssuer");
    openapiFields.add("claimOriginalIssuer");
    openapiFields.add("operator");
    openapiFields.add("value");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("claimType");
    openapiRequiredFields.add("claimValueType");
    openapiRequiredFields.add("operator");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to IfIdentityClaimExpression
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!IfIdentityClaimExpression.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in IfIdentityClaimExpression is not found in the empty JSON string", IfIdentityClaimExpression.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : IfIdentityClaimExpression.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("claimType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `claimType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("claimType").toString()));
      }
      if (!jsonObj.get("claimValueType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `claimValueType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("claimValueType").toString()));
      }
      if ((jsonObj.get("claimIssuer") != null && !jsonObj.get("claimIssuer").isJsonNull()) && !jsonObj.get("claimIssuer").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `claimIssuer` to be a primitive type in the JSON string but got `%s`", jsonObj.get("claimIssuer").toString()));
      }
      if ((jsonObj.get("claimOriginalIssuer") != null && !jsonObj.get("claimOriginalIssuer").isJsonNull()) && !jsonObj.get("claimOriginalIssuer").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `claimOriginalIssuer` to be a primitive type in the JSON string but got `%s`", jsonObj.get("claimOriginalIssuer").toString()));
      }
      if ((jsonObj.get("value") != null && !jsonObj.get("value").isJsonNull()) && !jsonObj.get("value").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `value` to be a primitive type in the JSON string but got `%s`", jsonObj.get("value").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!IfIdentityClaimExpression.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'IfIdentityClaimExpression' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<IfIdentityClaimExpression> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(IfIdentityClaimExpression.class));

       return (TypeAdapter<T>) new TypeAdapter<IfIdentityClaimExpression>() {
           @Override
           public void write(JsonWriter out, IfIdentityClaimExpression value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public IfIdentityClaimExpression read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of IfIdentityClaimExpression given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of IfIdentityClaimExpression
  * @throws IOException if the JSON string is invalid with respect to IfIdentityClaimExpression
  */
  public static IfIdentityClaimExpression fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, IfIdentityClaimExpression.class);
  }

 /**
  * Convert an instance of IfIdentityClaimExpression to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
