/*
 * FINBOURNE Access Management API
 *
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.access.model;

import java.util.Objects;
import com.finbourne.access.model.ActionId;
import com.finbourne.access.model.SelectorDefinition;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.finbourne.access.JSON;

/**
 * PolicySelectorDefinition
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class PolicySelectorDefinition {
  public static final String SERIALIZED_NAME_IDENTITY_RESTRICTION = "identityRestriction";
  @SerializedName(SERIALIZED_NAME_IDENTITY_RESTRICTION)
  private Map<String, String> identityRestriction;

  public static final String SERIALIZED_NAME_RESTRICTION_SELECTORS = "restrictionSelectors";
  @SerializedName(SERIALIZED_NAME_RESTRICTION_SELECTORS)
  private List<SelectorDefinition> restrictionSelectors;

  public static final String SERIALIZED_NAME_ACTIONS = "actions";
  @SerializedName(SERIALIZED_NAME_ACTIONS)
  private List<ActionId> actions = new ArrayList<>();

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public PolicySelectorDefinition() {
  }

  public PolicySelectorDefinition identityRestriction(Map<String, String> identityRestriction) {
    
    this.identityRestriction = identityRestriction;
    return this;
  }

  public PolicySelectorDefinition putIdentityRestrictionItem(String key, String identityRestrictionItem) {
    if (this.identityRestriction == null) {
      this.identityRestriction = new HashMap<>();
    }
    this.identityRestriction.put(key, identityRestrictionItem);
    return this;
  }

   /**
   * Get identityRestriction
   * @return identityRestriction
  **/
  @jakarta.annotation.Nullable
  public Map<String, String> getIdentityRestriction() {
    return identityRestriction;
  }


  public void setIdentityRestriction(Map<String, String> identityRestriction) {
    this.identityRestriction = identityRestriction;
  }


  public PolicySelectorDefinition restrictionSelectors(List<SelectorDefinition> restrictionSelectors) {
    
    this.restrictionSelectors = restrictionSelectors;
    return this;
  }

  public PolicySelectorDefinition addRestrictionSelectorsItem(SelectorDefinition restrictionSelectorsItem) {
    if (this.restrictionSelectors == null) {
      this.restrictionSelectors = new ArrayList<>();
    }
    this.restrictionSelectors.add(restrictionSelectorsItem);
    return this;
  }

   /**
   * Get restrictionSelectors
   * @return restrictionSelectors
  **/
  @jakarta.annotation.Nullable
  public List<SelectorDefinition> getRestrictionSelectors() {
    return restrictionSelectors;
  }


  public void setRestrictionSelectors(List<SelectorDefinition> restrictionSelectors) {
    this.restrictionSelectors = restrictionSelectors;
  }


  public PolicySelectorDefinition actions(List<ActionId> actions) {
    
    this.actions = actions;
    return this;
  }

  public PolicySelectorDefinition addActionsItem(ActionId actionsItem) {
    if (this.actions == null) {
      this.actions = new ArrayList<>();
    }
    this.actions.add(actionsItem);
    return this;
  }

   /**
   * Get actions
   * @return actions
  **/
  @jakarta.annotation.Nonnull
  public List<ActionId> getActions() {
    return actions;
  }


  public void setActions(List<ActionId> actions) {
    this.actions = actions;
  }


  public PolicySelectorDefinition name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @jakarta.annotation.Nullable
  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public PolicySelectorDefinition description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @jakarta.annotation.Nullable
  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PolicySelectorDefinition policySelectorDefinition = (PolicySelectorDefinition) o;
    return Objects.equals(this.identityRestriction, policySelectorDefinition.identityRestriction) &&
        Objects.equals(this.restrictionSelectors, policySelectorDefinition.restrictionSelectors) &&
        Objects.equals(this.actions, policySelectorDefinition.actions) &&
        Objects.equals(this.name, policySelectorDefinition.name) &&
        Objects.equals(this.description, policySelectorDefinition.description);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(identityRestriction, restrictionSelectors, actions, name, description);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PolicySelectorDefinition {\n");
    sb.append("    identityRestriction: ").append(toIndentedString(identityRestriction)).append("\n");
    sb.append("    restrictionSelectors: ").append(toIndentedString(restrictionSelectors)).append("\n");
    sb.append("    actions: ").append(toIndentedString(actions)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("identityRestriction");
    openapiFields.add("restrictionSelectors");
    openapiFields.add("actions");
    openapiFields.add("name");
    openapiFields.add("description");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("actions");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to PolicySelectorDefinition
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PolicySelectorDefinition.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PolicySelectorDefinition is not found in the empty JSON string", PolicySelectorDefinition.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : PolicySelectorDefinition.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("restrictionSelectors") != null && !jsonObj.get("restrictionSelectors").isJsonNull()) {
        JsonArray jsonArrayrestrictionSelectors = jsonObj.getAsJsonArray("restrictionSelectors");
        if (jsonArrayrestrictionSelectors != null) {
          // ensure the json data is an array
          if (!jsonObj.get("restrictionSelectors").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `restrictionSelectors` to be an array in the JSON string but got `%s`", jsonObj.get("restrictionSelectors").toString()));
          }

          // validate the optional field `restrictionSelectors` (array)
          for (int i = 0; i < jsonArrayrestrictionSelectors.size(); i++) {
            SelectorDefinition.validateJsonElement(jsonArrayrestrictionSelectors.get(i));
          };
        }
      }
      // ensure the json data is an array
      if (!jsonObj.get("actions").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `actions` to be an array in the JSON string but got `%s`", jsonObj.get("actions").toString()));
      }

      JsonArray jsonArrayactions = jsonObj.getAsJsonArray("actions");
      // validate the required field `actions` (array)
      for (int i = 0; i < jsonArrayactions.size(); i++) {
        ActionId.validateJsonElement(jsonArrayactions.get(i));
      };
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("description") != null && !jsonObj.get("description").isJsonNull()) && !jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PolicySelectorDefinition.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PolicySelectorDefinition' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PolicySelectorDefinition> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PolicySelectorDefinition.class));

       return (TypeAdapter<T>) new TypeAdapter<PolicySelectorDefinition>() {
           @Override
           public void write(JsonWriter out, PolicySelectorDefinition value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PolicySelectorDefinition read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PolicySelectorDefinition given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PolicySelectorDefinition
  * @throws IOException if the JSON string is invalid with respect to PolicySelectorDefinition
  */
  public static PolicySelectorDefinition fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PolicySelectorDefinition.class);
  }

 /**
  * Convert an instance of PolicySelectorDefinition to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
