/*
 * FINBOURNE Access Management API
 *
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.access.model;

import java.util.Objects;
import com.finbourne.access.model.ForSpec;
import com.finbourne.access.model.Grant;
import com.finbourne.access.model.HowSpec;
import com.finbourne.access.model.IfExpression;
import com.finbourne.access.model.Link;
import com.finbourne.access.model.PolicyId;
import com.finbourne.access.model.SelectorDefinition;
import com.finbourne.access.model.TemplateMetadata;
import com.finbourne.access.model.WhenSpec;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.finbourne.access.JSON;

/**
 * Response object from the policy API
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class PolicyResponse {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private PolicyId id;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_APPLICATIONS = "applications";
  @SerializedName(SERIALIZED_NAME_APPLICATIONS)
  private List<String> applications;

  public static final String SERIALIZED_NAME_GRANT = "grant";
  @SerializedName(SERIALIZED_NAME_GRANT)
  private Grant grant;

  public static final String SERIALIZED_NAME_SELECTORS = "selectors";
  @SerializedName(SERIALIZED_NAME_SELECTORS)
  private List<SelectorDefinition> selectors;

  public static final String SERIALIZED_NAME_FOR = "for";
  @SerializedName(SERIALIZED_NAME_FOR)
  private List<ForSpec> _for;

  public static final String SERIALIZED_NAME_IF = "if";
  @SerializedName(SERIALIZED_NAME_IF)
  private List<IfExpression> _if;

  public static final String SERIALIZED_NAME_WHEN = "when";
  @SerializedName(SERIALIZED_NAME_WHEN)
  private WhenSpec when;

  public static final String SERIALIZED_NAME_HOW = "how";
  @SerializedName(SERIALIZED_NAME_HOW)
  private HowSpec how;

  public static final String SERIALIZED_NAME_TEMPLATE_METADATA = "templateMetadata";
  @SerializedName(SERIALIZED_NAME_TEMPLATE_METADATA)
  private TemplateMetadata templateMetadata;

  public static final String SERIALIZED_NAME_LINKS = "links";
  @SerializedName(SERIALIZED_NAME_LINKS)
  private List<Link> links;

  public PolicyResponse() {
  }

  public PolicyResponse id(PolicyId id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @jakarta.annotation.Nullable
  public PolicyId getId() {
    return id;
  }


  public void setId(PolicyId id) {
    this.id = id;
  }


  public PolicyResponse description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Description of what the policy is entitling
   * @return description
  **/
  @jakarta.annotation.Nullable
  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public PolicyResponse applications(List<String> applications) {
    
    this.applications = applications;
    return this;
  }

  public PolicyResponse addApplicationsItem(String applicationsItem) {
    if (this.applications == null) {
      this.applications = new ArrayList<>();
    }
    this.applications.add(applicationsItem);
    return this;
  }

   /**
   * Applications to which the policy applies
   * @return applications
  **/
  @jakarta.annotation.Nullable
  public List<String> getApplications() {
    return applications;
  }


  public void setApplications(List<String> applications) {
    this.applications = applications;
  }


  public PolicyResponse grant(Grant grant) {
    
    this.grant = grant;
    return this;
  }

   /**
   * Get grant
   * @return grant
  **/
  @jakarta.annotation.Nullable
  public Grant getGrant() {
    return grant;
  }


  public void setGrant(Grant grant) {
    this.grant = grant;
  }


  public PolicyResponse selectors(List<SelectorDefinition> selectors) {
    
    this.selectors = selectors;
    return this;
  }

  public PolicyResponse addSelectorsItem(SelectorDefinition selectorsItem) {
    if (this.selectors == null) {
      this.selectors = new ArrayList<>();
    }
    this.selectors.add(selectorsItem);
    return this;
  }

   /**
   * Selectors that this policy will be applied to
   * @return selectors
  **/
  @jakarta.annotation.Nullable
  public List<SelectorDefinition> getSelectors() {
    return selectors;
  }


  public void setSelectors(List<SelectorDefinition> selectors) {
    this.selectors = selectors;
  }


  public PolicyResponse _for(List<ForSpec> _for) {
    
    this._for = _for;
    return this;
  }

  public PolicyResponse addForItem(ForSpec _forItem) {
    if (this._for == null) {
      this._for = new ArrayList<>();
    }
    this._for.add(_forItem);
    return this;
  }

   /**
   * \&quot;For Specification\&quot; for when the policy is to be applied
   * @return _for
  **/
  @jakarta.annotation.Nullable
  public List<ForSpec> getFor() {
    return _for;
  }


  public void setFor(List<ForSpec> _for) {
    this._for = _for;
  }


  public PolicyResponse _if(List<IfExpression> _if) {
    
    this._if = _if;
    return this;
  }

  public PolicyResponse addIfItem(IfExpression _ifItem) {
    if (this._if == null) {
      this._if = new ArrayList<>();
    }
    this._if.add(_ifItem);
    return this;
  }

   /**
   * \&quot;If Specification\&quot; for when the policy is to be applied
   * @return _if
  **/
  @jakarta.annotation.Nullable
  public List<IfExpression> getIf() {
    return _if;
  }


  public void setIf(List<IfExpression> _if) {
    this._if = _if;
  }


  public PolicyResponse when(WhenSpec when) {
    
    this.when = when;
    return this;
  }

   /**
   * Get when
   * @return when
  **/
  @jakarta.annotation.Nullable
  public WhenSpec getWhen() {
    return when;
  }


  public void setWhen(WhenSpec when) {
    this.when = when;
  }


  public PolicyResponse how(HowSpec how) {
    
    this.how = how;
    return this;
  }

   /**
   * Get how
   * @return how
  **/
  @jakarta.annotation.Nullable
  public HowSpec getHow() {
    return how;
  }


  public void setHow(HowSpec how) {
    this.how = how;
  }


  public PolicyResponse templateMetadata(TemplateMetadata templateMetadata) {
    
    this.templateMetadata = templateMetadata;
    return this;
  }

   /**
   * Get templateMetadata
   * @return templateMetadata
  **/
  @jakarta.annotation.Nullable
  public TemplateMetadata getTemplateMetadata() {
    return templateMetadata;
  }


  public void setTemplateMetadata(TemplateMetadata templateMetadata) {
    this.templateMetadata = templateMetadata;
  }


  public PolicyResponse links(List<Link> links) {
    
    this.links = links;
    return this;
  }

  public PolicyResponse addLinksItem(Link linksItem) {
    if (this.links == null) {
      this.links = new ArrayList<>();
    }
    this.links.add(linksItem);
    return this;
  }

   /**
   * Get links
   * @return links
  **/
  @jakarta.annotation.Nullable
  public List<Link> getLinks() {
    return links;
  }


  public void setLinks(List<Link> links) {
    this.links = links;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PolicyResponse policyResponse = (PolicyResponse) o;
    return Objects.equals(this.id, policyResponse.id) &&
        Objects.equals(this.description, policyResponse.description) &&
        Objects.equals(this.applications, policyResponse.applications) &&
        Objects.equals(this.grant, policyResponse.grant) &&
        Objects.equals(this.selectors, policyResponse.selectors) &&
        Objects.equals(this._for, policyResponse._for) &&
        Objects.equals(this._if, policyResponse._if) &&
        Objects.equals(this.when, policyResponse.when) &&
        Objects.equals(this.how, policyResponse.how) &&
        Objects.equals(this.templateMetadata, policyResponse.templateMetadata) &&
        Objects.equals(this.links, policyResponse.links);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, description, applications, grant, selectors, _for, _if, when, how, templateMetadata, links);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PolicyResponse {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    applications: ").append(toIndentedString(applications)).append("\n");
    sb.append("    grant: ").append(toIndentedString(grant)).append("\n");
    sb.append("    selectors: ").append(toIndentedString(selectors)).append("\n");
    sb.append("    _for: ").append(toIndentedString(_for)).append("\n");
    sb.append("    _if: ").append(toIndentedString(_if)).append("\n");
    sb.append("    when: ").append(toIndentedString(when)).append("\n");
    sb.append("    how: ").append(toIndentedString(how)).append("\n");
    sb.append("    templateMetadata: ").append(toIndentedString(templateMetadata)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("description");
    openapiFields.add("applications");
    openapiFields.add("grant");
    openapiFields.add("selectors");
    openapiFields.add("for");
    openapiFields.add("if");
    openapiFields.add("when");
    openapiFields.add("how");
    openapiFields.add("templateMetadata");
    openapiFields.add("links");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to PolicyResponse
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PolicyResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PolicyResponse is not found in the empty JSON string", PolicyResponse.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `id`
      if (jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) {
        PolicyId.validateJsonElement(jsonObj.get("id"));
      }
      if ((jsonObj.get("description") != null && !jsonObj.get("description").isJsonNull()) && !jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("applications") != null && !jsonObj.get("applications").isJsonNull() && !jsonObj.get("applications").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `applications` to be an array in the JSON string but got `%s`", jsonObj.get("applications").toString()));
      }
      if (jsonObj.get("selectors") != null && !jsonObj.get("selectors").isJsonNull()) {
        JsonArray jsonArrayselectors = jsonObj.getAsJsonArray("selectors");
        if (jsonArrayselectors != null) {
          // ensure the json data is an array
          if (!jsonObj.get("selectors").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `selectors` to be an array in the JSON string but got `%s`", jsonObj.get("selectors").toString()));
          }

          // validate the optional field `selectors` (array)
          for (int i = 0; i < jsonArrayselectors.size(); i++) {
            SelectorDefinition.validateJsonElement(jsonArrayselectors.get(i));
          };
        }
      }
      if (jsonObj.get("for") != null && !jsonObj.get("for").isJsonNull()) {
        JsonArray jsonArray_for = jsonObj.getAsJsonArray("for");
        if (jsonArray_for != null) {
          // ensure the json data is an array
          if (!jsonObj.get("for").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `for` to be an array in the JSON string but got `%s`", jsonObj.get("for").toString()));
          }

          // validate the optional field `for` (array)
          for (int i = 0; i < jsonArray_for.size(); i++) {
            ForSpec.validateJsonElement(jsonArray_for.get(i));
          };
        }
      }
      if (jsonObj.get("if") != null && !jsonObj.get("if").isJsonNull()) {
        JsonArray jsonArray_if = jsonObj.getAsJsonArray("if");
        if (jsonArray_if != null) {
          // ensure the json data is an array
          if (!jsonObj.get("if").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `if` to be an array in the JSON string but got `%s`", jsonObj.get("if").toString()));
          }

          // validate the optional field `if` (array)
          for (int i = 0; i < jsonArray_if.size(); i++) {
            IfExpression.validateJsonElement(jsonArray_if.get(i));
          };
        }
      }
      // validate the optional field `when`
      if (jsonObj.get("when") != null && !jsonObj.get("when").isJsonNull()) {
        WhenSpec.validateJsonElement(jsonObj.get("when"));
      }
      // validate the optional field `how`
      if (jsonObj.get("how") != null && !jsonObj.get("how").isJsonNull()) {
        HowSpec.validateJsonElement(jsonObj.get("how"));
      }
      // validate the optional field `templateMetadata`
      if (jsonObj.get("templateMetadata") != null && !jsonObj.get("templateMetadata").isJsonNull()) {
        TemplateMetadata.validateJsonElement(jsonObj.get("templateMetadata"));
      }
      if (jsonObj.get("links") != null && !jsonObj.get("links").isJsonNull()) {
        JsonArray jsonArraylinks = jsonObj.getAsJsonArray("links");
        if (jsonArraylinks != null) {
          // ensure the json data is an array
          if (!jsonObj.get("links").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `links` to be an array in the JSON string but got `%s`", jsonObj.get("links").toString()));
          }

          // validate the optional field `links` (array)
          for (int i = 0; i < jsonArraylinks.size(); i++) {
            Link.validateJsonElement(jsonArraylinks.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PolicyResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PolicyResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PolicyResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PolicyResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<PolicyResponse>() {
           @Override
           public void write(JsonWriter out, PolicyResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PolicyResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PolicyResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PolicyResponse
  * @throws IOException if the JSON string is invalid with respect to PolicyResponse
  */
  public static PolicyResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PolicyResponse.class);
  }

 /**
  * Convert an instance of PolicyResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
