/*
 * FINBOURNE Access Management API
 *
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.access.model;

import java.util.Objects;
import com.finbourne.access.model.NonTransitiveSupervisorRoleResource;
import com.finbourne.access.model.PolicyIdRoleResource;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.finbourne.access.JSON;

/**
 * RoleResourceRequest
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class RoleResourceRequest {
  public static final String SERIALIZED_NAME_NON_TRANSITIVE_SUPERVISOR_ROLE_RESOURCE = "nonTransitiveSupervisorRoleResource";
  @SerializedName(SERIALIZED_NAME_NON_TRANSITIVE_SUPERVISOR_ROLE_RESOURCE)
  private NonTransitiveSupervisorRoleResource nonTransitiveSupervisorRoleResource;

  public static final String SERIALIZED_NAME_POLICY_ID_ROLE_RESOURCE = "policyIdRoleResource";
  @SerializedName(SERIALIZED_NAME_POLICY_ID_ROLE_RESOURCE)
  private PolicyIdRoleResource policyIdRoleResource;

  public RoleResourceRequest() {
  }

  public RoleResourceRequest nonTransitiveSupervisorRoleResource(NonTransitiveSupervisorRoleResource nonTransitiveSupervisorRoleResource) {
    
    this.nonTransitiveSupervisorRoleResource = nonTransitiveSupervisorRoleResource;
    return this;
  }

   /**
   * Get nonTransitiveSupervisorRoleResource
   * @return nonTransitiveSupervisorRoleResource
  **/
  @jakarta.annotation.Nullable
  public NonTransitiveSupervisorRoleResource getNonTransitiveSupervisorRoleResource() {
    return nonTransitiveSupervisorRoleResource;
  }


  public void setNonTransitiveSupervisorRoleResource(NonTransitiveSupervisorRoleResource nonTransitiveSupervisorRoleResource) {
    this.nonTransitiveSupervisorRoleResource = nonTransitiveSupervisorRoleResource;
  }


  public RoleResourceRequest policyIdRoleResource(PolicyIdRoleResource policyIdRoleResource) {
    
    this.policyIdRoleResource = policyIdRoleResource;
    return this;
  }

   /**
   * Get policyIdRoleResource
   * @return policyIdRoleResource
  **/
  @jakarta.annotation.Nullable
  public PolicyIdRoleResource getPolicyIdRoleResource() {
    return policyIdRoleResource;
  }


  public void setPolicyIdRoleResource(PolicyIdRoleResource policyIdRoleResource) {
    this.policyIdRoleResource = policyIdRoleResource;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RoleResourceRequest roleResourceRequest = (RoleResourceRequest) o;
    return Objects.equals(this.nonTransitiveSupervisorRoleResource, roleResourceRequest.nonTransitiveSupervisorRoleResource) &&
        Objects.equals(this.policyIdRoleResource, roleResourceRequest.policyIdRoleResource);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nonTransitiveSupervisorRoleResource, policyIdRoleResource);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RoleResourceRequest {\n");
    sb.append("    nonTransitiveSupervisorRoleResource: ").append(toIndentedString(nonTransitiveSupervisorRoleResource)).append("\n");
    sb.append("    policyIdRoleResource: ").append(toIndentedString(policyIdRoleResource)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("nonTransitiveSupervisorRoleResource");
    openapiFields.add("policyIdRoleResource");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to RoleResourceRequest
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!RoleResourceRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in RoleResourceRequest is not found in the empty JSON string", RoleResourceRequest.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `nonTransitiveSupervisorRoleResource`
      if (jsonObj.get("nonTransitiveSupervisorRoleResource") != null && !jsonObj.get("nonTransitiveSupervisorRoleResource").isJsonNull()) {
        NonTransitiveSupervisorRoleResource.validateJsonElement(jsonObj.get("nonTransitiveSupervisorRoleResource"));
      }
      // validate the optional field `policyIdRoleResource`
      if (jsonObj.get("policyIdRoleResource") != null && !jsonObj.get("policyIdRoleResource").isJsonNull()) {
        PolicyIdRoleResource.validateJsonElement(jsonObj.get("policyIdRoleResource"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!RoleResourceRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'RoleResourceRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<RoleResourceRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(RoleResourceRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<RoleResourceRequest>() {
           @Override
           public void write(JsonWriter out, RoleResourceRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public RoleResourceRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of RoleResourceRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of RoleResourceRequest
  * @throws IOException if the JSON string is invalid with respect to RoleResourceRequest
  */
  public static RoleResourceRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, RoleResourceRequest.class);
  }

 /**
  * Convert an instance of RoleResourceRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
